# Module: mysql
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.3/metricbeat-module-mysql.html

- module: mysql
  metricsets:
    - status
    - galera_status
  period: 15s
  hosts: ["tcp(127.0.0.1:3306)/"]
  username: datadog
  password: DataD0gGCP!

