# Module: postgresql
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.3/metricbeat-module-postgresql.html

- module: postgresql
  metricsets:
    - database
    - bgwriter
    - activity
    - statement
  period: 10s
  hosts: ["postgres://localhost:5432/"]
  username: datadog
  password: DataD0gGCP!
