---

  - name: Debian - Ensure apt-transport-https is installed
    apt: name=apt-transport-https state=present cache_valid_time=86400

  - name: Debian - Add Beats repository key
    apt_key:
      url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
      state: present

  - name: Debian - add beats repository
    apt_repository: 
      repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main" 
      state: present
      update_cache: yes

  - name: Debian - Ensure metricbeat is installed
    apt: 
      name: metricbeat
      state: latest
      update_cache: yes

