---

- name: ProxySQL Service "{{ service_state }}"
  become: true
  systemd:
    name: "{{ service_name }}"
    state: "{{ service_state }}"
    enabled: false
    daemon_reload: true
  when: disable_proxysql_service and stop_proxysql_service
  tags:
    - proxysql-service-disable
    - proxysql-service-stop
    - proxysql-service
