---


- name: "Create ProxySQL Hostgroup routing rules"
  proxysql_replication_hostgroups:
    login_host: "{{ proxysql_admin_host }}"
    login_port: "{{ proxysql_admin_port }}"
    login_user: "{{ proxysql_admin_user }}"
    login_password: "{{ proxysql_admin_password }}"
    writer_hostgroup: "{{ item.proxysql_writer_hostgroup }}"
    reader_hostgroup: "{{ item.proxysql_reader_hostgroup }}"
    state: "{{ item.proxysql_hostgroup_state }}"
    load_to_runtime: True
    save_to_disk: True
  with_items: 
    - "{{ proxysql_mysql_hostgroups }}" 
  tags: 
    - proxysql-mysql-hostgroups
