---

- name: Remove ProxySQL user for MySQL
  proxysql_mysql_users:
          login_host: "{{ proxysql_admin_host }}"
          login_port: "{{ proxysql_admin_port }}"
          login_user: "{{ proxysql_admin_user }}"
          login_password: "{{ proxysql_admin_password }}"
          username: "{{ item.mysql_username }}"
          state: absent
          load_to_runtime: True
          save_to_disk: True
  when: proxysql_remove_user
  with_items:
    - "{{ proxysql_remove_users }}"
  tags:
    - proxysql-remove-users
