---

- name: Remove ProxySQL user for MySQL
  proxysql_mysql_users:
          login_host: "{{ proxysql_login_host }}"
          login_port: "{{ proxysql_login_port }}"
          login_user: "{{ proxysql_login_user }}"
          login_password: "{{ proxysql_admin_password }}"
          username: "{{ mysql_username }}"
          default_hostgroup: "{{ mysql_user_default_hostgroup }}"
          state: absent
          load_to_runtime: True
          save_to_disk: True
  when: proxysql_remove_user
  with_items:
    - "{{ proxysql_remove_users }}"
  tags:
    - proxysql-remove-users
