---


 - name: ProxySQL node setup 
   hosts: proxysql
   tasks:
     - include_role:
         name: ~/git/ansible-proxysql/roles/proxysql_os_common
     - include_role:
         name: ~/git/ansible-proxysql/roles/proxysql_os_user
     - include_role:
         name: ~/git/ansible-proxysql/roles/proxysql_add_bash_profile
     - include_role:
         name: ~/git/ansible-proxysql/roles/proxysql_bin_install
     - include_role:
         name: ~/git/ansible-proxysql/roles/proxysql_os_kernel_tuning
     - include_role:
         name: ~/git/ansible-proxysql/roles/proxysql_config_setup
     - include_role:
         name: ~/git/ansible-proxysql/roles/proxysql_service_start
     - include_role:
         name: ~/git/ansible-proxysql/roles/proxysql_set_server_variable
     - include_role:
         name: ~/git/ansible-proxysql/roles/proxysql_service_stop
     - include_role:
         name: ~/git/ansible-proxysql/roles/proxysql_service_start
     - include_role:
         name: ~/git/ansible-proxysql/roles/proxysql_mysql_user
     - include_role:
         name: ~/git/ansible-proxysql/roles/proxysql_mysql_server 
     - include_role:
         name: ~/git/ansible-proxysql/roles/proxysql_mysql_query_rule
